# Generated by Django 2.2.4 on 2020-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
