# Generated by Django 2.2.4 on 2020-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
    ]
